

export const SIGN_UP="SIGN_UP";
export const SIGN_UP_FAIL="SIGN_UP_FAIL";
export const SIGN_UP_SUCCES="SIGN_UP_SUCCES";
export const LOGIN="LOGIN";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGIN_SUCCES="LOGIN_SUCCES";
export const GET_PROFILE="GET_PROFILE";
export const GET_PROFILE_FAIL="GET_PROFILE_FAIL";
export const GET_PROFILE_SUCCES="GET_PROFILE_SUCCES";
export const GET_PRODUCT="GET_PRODUCT";
export const GET_PRODUCT_FAIL="GET_PRODUCT_FAIL";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const ADD_PRODUCT="ADD_PRODUCT";
export const ADD_PRODUCT_FAIL="ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";
export const EDIT_PRODUCT="EDIT_PRODUCT";
export const EDIT_PRODUCT_FAIL="EDIT_PRODUCT_FAIL";
export const EDIT_PRODUCT_SUCCESS="EDIT_PRODUCT_SUCCESS";
export const ADD_PRODUCT_CART="ADD_PRODUCT_CART";
export const ADD_PRODUCT_CART_FAIL="ADD_PRODUCT_CART_FAIL";
export const ADD_PRODUCT_CART_SUCCESS="ADD_PRODUCT_CART_SUCCESS";
export const ADD_ITEM ="ADD_ITEM";
export const LOGOUT="LOGOUT";
export const DELETE_ITEM="DELETE_ITEM"



